name: Deploy validate_files Environment

on:
  push:
    branches:
      - validate_files  # Ce workflow s'exécute uniquement pour la branche uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Install Python dependencies
          run: |
           pip install pytest  # Installe pytest pour exécuter les tests

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
           python-version: '3.x'  # Spécifie la version de Python      

        
        - name: Run Python script
          run: |
           python testScript.py  # Exécute ton script Python

        - name: Deploy to GitHub Pages (validate_files)
          uses: peaceiris/actions-gh-pages@v3
          with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./  # Dossier source, racine du dépôt
           destination_dir: validate_files  # Déploie les fichiers dans le dossier /uat dans gh-pages